import os
FLASK_DEBUG = os.environ.get('FLASK_DEBUG', True)
MAIL_PASSWORD=os.environ.get('MAIL_PASSWORD','fkoh xfak aizr dkwo')
my_email=os.environ.get('my_email','flask772@gmail.com')
BaseURL=os.environ.get('BaseURL','http://localhost:3000/query-ui')
MYSQL_USER = os.getenv('MYSQL_USER')
MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD')
MYSQL_HOST = os.getenv('MYSQL_HOST','localhost')
MYSQL_PORT = os.getenv('MYSQL_PORT', '3306')
MYSQL_DATABASE = os.getenv('MYSQL_DATABASE')
MONGO_USERNAME = os.getenv('MONGO_INITDB_ROOT_USERNAME')
MONGO_PASSWORD = os.getenv('MONGO_INITDB_ROOT_PASSWORD')
MONGO_HOST = os.getenv('MONGO_HOST','localhost')
MONGO_PORT = os.getenv('MONGO_PORT', '27017')
MONGO_DATABASE = os.getenv('MONGO_DATABASE')